### ISSUE TITLE
move .dotfiles to target?

### ISSUE THREAD

**Issue by davidmoten** [lgrignon/jsweet-maven-plugin#4]
When I build jsweet-quickstart that uses the maven plugin I end up with the following dot directories in the root directory of the project:

```
.jsweet
.generated
.ts
```
I'd prefer these files lived in `target` directory so that when `mvn clean` is called all state is gone (the usual exception for maven of course is that artifacts installed to `.m2/repository` remain). Do you see any impediment to moving these files to the `target` directory (and perhaps giving them non-dot names for visibility)? I think this should be the default behaviour.

**Comment by renaudpawlak** [comment]
It makes sense to me for (target/ts and target/js). It also makes sense that it becomes the default behavior of the Maven plugin (should it be also the default for the command line launcher, which can be used without Maven? Is it a problem to have 2 different defaults?).

In any case, these default values are set in the Maven plugin.

I am not so sure with the .jsweet directory because it contains the processed candies... normally, this directory is updated only when the project dependencies change. Removing it when cleaning might not be very efficient because it would force the candy processing again even when no dependencies change. However, it might be more intuitive for the programmers to see the jsweet directory there, and to remove all the state when cleaning... so I would also agree to move it to target/jsweet.

Note: I think that there might be a small bug here because .ts and .generated have the same purpose... one is empty? There should only be one or the other IMO... I would keep only target/ts by default...

Do you want to PR the Maven plugin or do you want us to take care of it?

**Comment by davidmoten** [comment]
>should it be also the default for the command line launcher

I don't think it matters that the command line launcher has different defaults.

>Do you want to PR the Maven plugin or do you want us to take care of it?

I'll happily leave this one to you guys as my understanding of `jsweet` is still pretty superficial. Thanks.

**Comment by lgrignon** [comment]
Done
