### ISSUE TITLE
Plugin will only copy candy bundle to target once

### ISSUE THREAD

**Issue by thw0rted** [lgrignon/jsweet-maven-plugin#41]
I am encountering a baffling issue.  Using [the attached pom.xml file](https://github.com/lgrignon/jsweet-maven-plugin/files/1938456/pom.xml.txt), I can build my library just fine, and the target specified by `candiesJsOut` (here, "target/candies2") will be populated with the `bundle.js` for the one candy dependency declared, j4ts.  Then I run `mvn clean generate-sources` a second time -- now my `target/ts` and `target/js` populate as before, and the `candies2` directory gets created... but it's empty.  If I change the name of the target, then `clean generate-sources`, the new directory gets a copy of the bundle, but the next clean/build cycle removes it.

Try it for yourself:

* mvn generate-sources
* ls target/candies --> has j4ts files
* mvn clean generate-sources 
* ls target/candies --> is empty
* Edit `candiesJsOut` property in POM to "candies2" or whatever
* mvn clean generate-sources 
* ls target/candies2 --> has files
* mvn clean generate-sources 
* ls target/candies --> is empty

**Comment by lgrignon** [comment]
Indeed, this is a bug. Probably the candy generation caching mechanism which doesn't regenerate after a clean.
I don't know if I could take care of this very soon, because I am already working on another issue for JSweet. Would you want to take a look? I think it is handled in the https://github.com/cincheo/jsweet/blob/master/transpiler/src/main/java/org/jsweet/transpiler/candy/CandyProcessor.java class

**Comment by lgrignon** [comment]
Did you find time to take a look?

**Comment by thw0rted** [comment]
If I'm honest, I'm probably going to have to take some time to get a deeper understanding of the transpiler's internals, which I'm unlikely to have the time for in the near future.  I'll keep this on my TODO list but I have a few deliverables to deal with first so it could be a while.  Sorry!

**Comment by lgrignon** [comment]
Actually this issue was much simpler than expected. You need to bind maven clean phase to JSweet's clean mojo.
For example: https://github.com/lgrignon/j4ts-example/blob/master/pom.xml#L92

I doubt @thw0rted is still interested in this :) hence closing this issue, but please feel free to reopen if problem persists with this technique

**Comment by thw0rted** [comment]
Oh wow, this takes me back.  I actually wound up using jsweet to transpile one medium-sized library and haven't been back to it since.  I still use the library, though, so... thanks!
